### ISSUE TITLE
Erstelle eine Tabelle -> Ali 

### ISSUE THREAD

**Issue by tBuddy00** [tBuddy00/htwd-se-example-teamproject#1]
**Ali**

=== Programmiersprachen Syntax  
1. Erstelle bitte eine **Tabelle** mit folgendem Inhalt:

Tabellenkopf in gleicher Reihenfolge: **Programmiersprache** **Beispiel**

Schreibe in die Spalte **Beispiel** das hier: "print" und die dazugehörige Syntax

**Comment by MahdiAlosh** [comment]
erledigt ;) ! @tBuddy00
