### ISSUE TITLE
Quell Code "JAVA" muss erstellt werden

### ISSUE THREAD

**Issue by MahdiAlosh** [tBuddy00/htwd-se-example-teamproject#4]
Taylaaaaan, 

====
fügst du mal bitte noch zusätzlichen Code-Abschnitt hinzu, in dem **_"helloWolrd" in java_** geschrieben wird.
====

Mit freundlichen Grüßen

Ali 
@tBuddy00

**Comment by tBuddy00** [comment]
Abgeschlossen 👯‍♀️
